project_id = "yqukwnyjqqfxqcuklluh"

[functions.generate-question]
verify_jwt = true

[functions.submit-result]
verify_jwt = true

[functions.get-user-stats]
verify_jwt = true

[functions.get-games]
verify_jwt = true

[functions.update-game-progress]
verify_jwt = true

[functions.seed-questions]
verify_jwt = true